import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/questions.ts",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        tomato: {
          1: "#fffcfc",
          2: "#fff8f7",
          3: "#feebe7",
          4: "#ffdcd3",
          5: "#ffcdc2",
          6: "#fdbdaf",
          7: "#f5a898",
          8: "#ec8e7b",
          9: "#e54d2e",
          10: "#dd4425",
          11: "#d13415",
          12: "#5c271f",
        },
        orange: {
          1: "#fefcfb",
          2: "#fff7ed",
          3: "#ffefd6",
          4: "#ffdfb5",
          5: "#ffd19a",
          6: "#ffc182",
          7: "#f5ae73",
          8: "#ec9455",
          9: "#f76b15",
          10: "#ef5f00",
          11: "#cc4e00",
          12: "#582d1d",
        },
        lime: {
          1: "#fcfdfa",
          2: "#f8faf3",
          3: "#eef6d6",
          4: "#e2f0bd",
          5: "#d3e7a6",
          6: "#c2da91",
          7: "#abc978",
          8: "#8db654",
          9: "#bdee63",
          10: "#b0e64c",
          11: "#5c7c2f",
          12: "#37401c",
        },
        red: {
          1: "#fffcfc",
          2: "#fff7f7",
          3: "#feebec",
          4: "#ffdbdc",
          5: "#ffcdce",
          6: "#fdbdbe",
          7: "#f4a9aa",
          8: "#eb8e90",
          9: "#e5484d",
          10: "#dc3e42",
          11: "#ce2c31",
          12: "#641723",
        },
        sage: {
          1: "#fbfdfc",
          2: "#f7f9f8",
          3: "#eef1f0",
          4: "#e6e9e8",
          5: "#dfe2e0",
          6: "#d7dad9",
          7: "#cbcfcd",
          8: "#b8bcba",
          9: "#868e8b",
          10: "#7c8481",
          11: "#5f6563",
          12: "#1a211e",
        },
        gold: {
          1: "#fdfdfc",
          2: "#faf9f2",
          3: "#f2f0e7",
          4: "#eae6db",
          5: "#e1dccf",
          6: "#d8d0bf",
          7: "#cbc0aa",
          8: "#b9a88d",
          9: "#978365",
          10: "#8c7a5e",
          11: "#71624b",
          12: "#3b352b",
        },
        sky: {
          1: "#f9feff",
          2: "#f1fafd",
          3: "#e1f6fd",
          4: "#d1f0fa",
          5: "#bee7f5",
          6: "#a9daed",
          7: "#8dcae3",
          8: "#60b3d7",
          9: "#7ce2fe",
          10: "#74daf8",
          11: "#00749e",
          12: "#1d3e56",
        },
        salmon: {
          1: "#fffcfc",
          2: "#fff7f7",
          3: "#feebea",
          4: "#ffdddc",
          5: "#ffcfcf",
          6: "#f9bfc0",
          7: "#f0acad",
          8: "#e69394",
          9: "#f45b69",
          10: "#e74d5d",
          11: "#c82f46",
          12: "#631922",
        },
        willow: {
          1: "#fcfdf9",
          2: "#f9faf0",
          3: "#f3f7cc",
          4: "#eaf0ae",
          5: "#e0e692",
          6: "#d2d87b",
          7: "#c0c661",
          8: "#abb027",
          9: "#a0a512",
          10: "#959900",
          11: "#747700",
          12: "#3c3f14",
        },
        cyan: {
          1: "#fafdfe",
          2: "#f2fafb",
          3: "#def7f9",
          4: "#caf1f6",
          5: "#b5e9f0",
          6: "#9ddde7",
          7: "#7dcedc",
          8: "#3db9cf",
          9: "#00a2c7",
          10: "#0797b9",
          11: "#107d98",
          12: "#0d3c48",
        },
        bronze: {
          1: "#fdfcfc",
          2: "#fdf7f5",
          3: "#f6edea",
          4: "#efe4df",
          5: "#e7d9d3",
          6: "#dfcdc5",
          7: "#d3bcb3",
          8: "#c2a499",
          9: "#a18072",
          10: "#957468",
          11: "#7d5e54",
          12: "#43302b",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
